import { ModeToggle } from "@/components/ModeToggle";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
       
      >
<ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="fixed top-2 right-2">

          {/* <ModeToggle /> */}
          </div>
        {children}

        </ThemeProvider>

      </body>
    </html>
  );
}
